Repository CA-G12/Api-Project-Bayan-asil-, pull requests merged in 2022-08, with the labels that each got.

#4 create html ,css,js files for meals page and drinks page
  drinks/drinks.css
  drinks/drinks.html
  drinks/drinks.js
  index.html
  meals/meals.css
  meals/meals.js
Labels: apparoved

#8 7 landing page
  index.html
  landing-page/landing.css
Labels: awaiting-review

#9 2 meals page create and style
  meals/meals.css
  meals/meals.html
Labels: apparoved

#12 create reusable file js and put the reusable functions
  reusable.js
Labels: apparoved

#13 add the functionality for meals page
  meals/meals.html
  meals/meals.js
Labels: awating-review

#15 add the functionality for drinks page
  drinks/drinks.css
  drinks/drinks.html
  drinks/drinks.js
Labels: awaiting-review

#18 creating read me file
  README.md
Labels: awaiting-review

#19 17 popup
  drinks/drinks.css
  drinks/drinks.html
  drinks/drinks.js
  meals/meals.css
  meals/meals.html
  meals/meals.js
Labels: apparoved

#21 some edites in design
  meals/meals.css
Labels: apparoved
